<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AsyncLength" targetNamespace="http://j2ee.netbeans.org/wsdl/AsyncLength/src/AsyncLength"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/AsyncLength/src/AsyncLength" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="ChangeLengthUnitRequest">
        <part name="LengthValue" type="xsd:double"/>
        <part name="fromLengthUnit" type="xsd:string"/>
        <part name="toLengthUnit" type="xsd:string"/>
    </message>
    <portType name="AsyncLengthPortType">
        <operation name="ChangeLengthUnit">
            <input name="input1" message="tns:ChangeLengthUnitRequest"/>
        </operation>
    </portType>
    <binding name="AsyncLengthBinding" type="tns:AsyncLengthPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ChangeLengthUnit">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/AsyncLength/src/AsyncLength"/>
            </input>
        </operation>
    </binding>
    <service name="AsyncLengthService">
        <port name="AsyncLengthPort" binding="tns:AsyncLengthBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/AsyncLengthService/AsyncLengthPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="AsyncLength">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="AsyncLengthPortTypeRole" portType="tns:AsyncLengthPortType"/>
    </plnk:partnerLinkType>
</definitions>
