<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServiceMaster.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ServiceMaster.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ServiceMaster.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="GeodataService">
    <import location="http://services.deserthail.com/GeodataService/ServiceMaster.asmx?WSDL" namespace="GeodataService"/>
    <plnk:partnerLinkType name="ServiceMasterSoapLinkType">
        <plnk:role name="ServiceMasterSoapRole" portType="ns:ServiceMasterSoap"/>
    </plnk:partnerLinkType>
</definitions>
